changelog:
  categories:
    - title: 🎉 Features
      labels:
        - faeture
    - title: ✨ Refinements
      labels:
        - refinement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🌏 Translations
      labels:
        - translation
    - title: 🏠 Maintenance
      labels:
        - maintenance
    - title: 📝 Documentation
      labels:
        - documentation
    - title: Others
      labels:
        - "*"
