changelog:
  categories:
    - title: 🎉 Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixs
      labels:
        - bug
    - title: 🏠 Maintenance
      labels:
        - maintenance
    - title: 📝 Documentation
      labels:
        - documentation
    - title: Others
      labels:
        - "*"
